# Generated by Django 5.0.7 on 2024-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=50, verbose_name='Header Title')),
                ('phone', models.IntegerField(blank=True, verbose_name='Phone Number')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
                ('open_worked', models.CharField(blank=True, max_length=20, verbose_name='Open Worked')),
                ('our_story', models.TextField(blank=True, verbose_name='Our Story')),
                ('our_slogan_title', models.CharField(blank=True, max_length=120, verbose_name='Our Slogan Title')),
                ('our_slogan_left', models.TextField(blank=True, verbose_name='Our Slogan Left')),
                ('our_slogan_right', models.TextField(blank=True, verbose_name='Our Slogan Right')),
                ('our_team_des', models.CharField(max_length=250, verbose_name='Meet Our Team Description')),
            ],
        ),
    ]
