# Generated by Django 5.0.7 on 2024-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_title',
            new_name='Home',
        ),
    ]
