# Generated by Django 5.0.7 on 2024-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='our_team_des',
            field=models.CharField(blank=True, max_length=250, verbose_name='Meet Our Team Description'),
        ),
    ]
