# Generated by Django 5.0.7 on 2024-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Slug'),
        ),
    ]
