# Generated by Django 5.0.7 on 2024-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='our_slogan_title_left',
            field=models.CharField(blank=True, max_length=120, verbose_name='Our Slogan Title Left'),
        ),
        migrations.AddField(
            model_name='home',
            name='our_slogan_title_right',
            field=models.CharField(blank=True, max_length=120, verbose_name='Our Slogan Title Right'),
        ),
    ]
