# Generated by Django 5.0.7 on 2024-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_home_our_slogan_title_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
