# Generated by Django 5.0.7 on 2024-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_home_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
